### ISSUE TITLE
Excel task pane add-in README.md displays PowerPoint info

### ISSUE THREAD

**Issue by alison-mk** [OfficeDev/Office-Samples#101]
On MacOS Ventura 13.6.9: 

I take these steps: 
Open Office Add-ins Development Kit 
Choose "Create a New Add-in" 
Choose "Excel Add-in" 
Choose "TypeScript" 
Create add-in 
The project is created and the README.md displays PowerPoint info. See screenshot. 

The project files are actually for Excel, but the README.md is incorrect. 

<img width="911" alt="image" src="https://github.com/user-attachments/assets/193a3948-30a1-487c-ae2b-67730b7120a6">

**Comment by hermanwenhe** [comment]
PR checked in. This bug will be fixed in next release.
