### ISSUE TITLE
Writing assistance sample runs with compilation error

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/Office-Samples#102]
When previewing the Writing Assistant sample through the dev kit, I get this error in the task pane:

![image](https://github.com/user-attachments/assets/f554ece9-e710-4f20-ab44-1098b3ddcab0)

**Comment by hermanwenhe** [comment]
Can you share the node/npm/react version?

**Comment by AlexJerabek** [comment]
I can't repro this anymore. I'll close the issue, but reopen it with the requested information if it happens again.
