### ISSUE TITLE
All samples contain an Outlook command

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/Office-Samples#98]
In the Excel and Word samples, there is a 'commands' folder. The command action being added is a mailbox notification action. This is confusing to have in an Excel or Word add-in. They should be removed across all the samples.

**Comment by hermanwenhe** [comment]
We'll delete these commands files. Actually this is a common issue among all office add-in templates. Check here: https://github.com/OfficeDev/Office-Addin-TaskPane/blob/yo-office/src/commands/commands.ts

**Comment by hermanwenhe** [comment]
PR: https://github.com/OfficeDev/Office-Samples/pull/110
